events {}
http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    upstream web_servers {
        # Round-robin load balancing
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;
        server_name works-on-my-machine.rip;
        # Redirect port 8080 to 8443 (HTTPS)
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name works-on-my-machine.rip;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        location / {
            proxy_pass http://web_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Access List
            allow 192.168.0.0/16;
            allow 127.0.0.1;
            allow 10.0.0.0/8;
            allow 172.16.0.0/12;
            deny all;
        }
    }
}
